---
title: 'MpBC Genomics Paper: Signature Figure'
author: "David Jenkins"
date: "7/23/2018"
output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    theme: "united"
---

## Load Packages

```{r packages, results='hide', message=FALSE, warning=FALSE}
library(RColorBrewer)
library(ComplexHeatmap)
library(multipanelfigure)
```

## Signatures {.tabset}

```{r data}
plotTraining <- function(output.data, pathway_number, pathway){
  row_order <- order(output.data$processed.data$S_matrix[,pathway_number],
                     decreasing = T)
  data <- output.data$processed.data$trainingData_sub[row_order,]
  prior <- output.data$processed.data$S_matrix[row_order,pathway_number]
  priorprob <- output.data$processed.data$Delta_matrix[row_order,pathway_number]
  data <- data[priorprob == 1,]
  prior <- prior[priorprob == 1]
  ha <- columnAnnotation(
    assign_pred = column_anno_barplot(
      output.data$mcmc.pos.mean.trainingData$beta_pos[,pathway_number],
      baseline = 0, bar_width=1, gp = gpar(fill = "purple")))
  colnames(data) <- gsub("_FOR_AKT", "", colnames(data))
  colnames(data) <- gsub("_18HR", "", colnames(data))
  colnames(data) <- gsub("_36HR", "", colnames(data))
  draw(rowAnnotation(
    barplotprior=row_anno_barplot(
      prior, baseline = 0, axis_direction="reverse", bar_width=1,
      gp = gpar(fill = ifelse(prior > 0, "#e6bbad", "#add8e6"),
                col = ifelse(prior > 0, "#8b0000", "#008b8b")), axis=T),
    width = unit(1.5, "cm"), gap=unit(0.1,"cm")) + 
    Heatmap(t(scale(t(data))),
            name=pathway,
            row_names_gp = gpar(fontsize = 8),
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = FALSE,
            show_column_names = TRUE),
    row_title = "            Change in Expression")
}


```

### AKT1

```{r akt, fig.width=4}
akt_res <- readRDS("../results/akt_gene_list_adaptS_FALSE/output.rds")
colnames(akt_res$processed.data$trainingData_sub)[4:6] <- c("AKT1-1", "AKT1-2", "AKT1-3")
aktplot <- plotTraining(akt_res, 1, "AKT1")
```

### BAD

```{r bad, fig.width=4}
bad_res <- readRDS("../results/bad_gene_list_adaptS_FALSE/output.rds")
badplot <- plotTraining(bad_res, 1, "BAD")
```

### BCL2L11

```{r bim, fig.width=4}
bim_res <- readRDS("../results/bim_gene_list_adaptS_FALSE/output.rds")
colnames(bim_res$processed.data$trainingData_sub)[4:6] <- c("BCL2L11-1", "BCL2L11-2", "BCL2L11-3")
bimplot <- plotTraining(bim_res, 1, "BCL2L11")
```

### HER2

```{r her2, fig.width=4}
her2_res <- readRDS("../results/her2_gene_list_adaptS_FALSE/output.rds")
her2plot <- plotTraining(her2_res, 1, "HER2")
```

### IGF1R

```{r igf1r, fig.width=4}
igf1r_res <- readRDS("../results/igf1r_gene_list_adaptS_FALSE/output.rds")
igf1rplot <- plotTraining(igf1r_res, 1, "IGF1R")
```

### KRASG12V

```{r krasgv, fig.width=4}
krasgv_res <- readRDS("../results/krasgv_gene_list_adaptS_FALSE/output.rds")
colnames(krasgv_res$processed.data$trainingData_sub)[4:6] <- c("KRASG12V-1", "KRASG12V-2", "KRASG12V-3")
krasplot <- plotTraining(krasgv_res, 1, "KRASG12V")
```

### RAF1

```{r raf, fig.width=4}
raf_res <- readRDS("../results/raf_gene_list_adaptS_FALSE/output.rds")
colnames(raf_res$processed.data$trainingData_sub)[4:6] <- c("RAF1-1", "RAF1-2", "RAF1-3")
rafplot <- plotTraining(raf_res, 1, "RAF1")
```

### SNAI1

```{r snail, fig.width=4}
snail_res <- readRDS("../results/snail_gene_list_adaptS_FALSE/output.rds")
colnames(snail_res$processed.data$trainingData_sub)[4:6] <- c("SNAI1-1", "SNAI1-2", "SNAI1-3")
snailplot <- plotTraining(snail_res, 1, "SNAI1")
```

## Big Plot

```{r bigplot, fig.width=13, fig.height=7, message=FALSE, warning=FALSE}
figure_signatures <- multi_panel_figure(
  width = 13,
  columns = 4,
  height = 7,
  rows = 2,
  figure_name = "figure_signatures",
  unit="inches")
figure_signatures <- fill_panel(figure_signatures, aktplot, scaling = "shrink")
figure_signatures <- fill_panel(figure_signatures, badplot, scaling = "shrink")
figure_signatures <- fill_panel(figure_signatures, bimplot, scaling = "shrink")
figure_signatures <- fill_panel(figure_signatures, her2plot, scaling = "shrink")
figure_signatures <- fill_panel(figure_signatures, igf1rplot, scaling = "shrink")
figure_signatures <- fill_panel(figure_signatures, krasplot, scaling = "shrink")
figure_signatures <- fill_panel(figure_signatures, rafplot, scaling = "shrink")
figure_signatures <- fill_panel(figure_signatures, snailplot, scaling = "shrink")

ggplot2::ggsave(
  "figure_2.pdf", figure_signatures,
  width = figure_width(figure_signatures, "in"),
  height = figure_height(figure_signatures, "in"))

figure_signatures
```
