---
title: "Correlation of ASSIGN Reduced Signatures and Optimized Signature"
author: "David Jenkins"
date: "5/11/2017"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme: "united"
---

```{r warning=FALSE, message=FALSE}
library(ggplot2)
library(reshape2)
library(dplyr)
library(gridExtra)

icbp_predictions <- read.table("../data/20161213_reanalysis_with_new_EGFR_icbp.predictions.txt", sep="\t", header=T)
tcga_predictions <- read.table("../data/20161213_reanalysis_with_new_EGFR_tcga.predictions.txt", sep="\t", header=T)

colnames(icbp_predictions) <- colnames(icbp_predictions) %>% strsplit("_") %>% lapply(function(x) paste(x[1],x[2], sep="_")) %>% unlist
colnames(tcga_predictions) <- colnames(tcga_predictions) %>% strsplit("_") %>% lapply(function(x) paste(x[1],x[2], sep="_")) %>% unlist
icbp_predictions$Sample <- rownames(icbp_predictions)
tcga_predictions$Sample <- rownames(tcga_predictions)
icbp_predictions_m <- melt(icbp_predictions)
tcga_predictions_m <- melt(tcga_predictions)
```

# Optimized Pathways vs. Other Lists {.tabset}

## ICBP

```{r warning=FALSE, message=FALSE, fig.height=12, fig.width=12}
get_path_cor <- function(indata, optimized, coly){
  corres <- as.numeric(cor.test(indata[,optimized], indata[,coly])$estimate)
  return(corres)
}

create_correlation_plot <- function(indata, optimized, coly){
  pathway <- toupper(unlist(strsplit(optimized, "_"))[1])
  optnum <-  unlist(strsplit(optimized, "_"))[2]
  compnum <- unlist(strsplit(coly, "_"))[2]
  corres <- as.numeric(cor.test(indata[,optimized], indata[,coly])$estimate)
  plot <- ggplot(indata, aes_string(x=optimized, y=coly)) +
    geom_point() + xlim(c(0,1)) + ylim(c(0,1)) + ggtitle(paste0("Pathway: ",pathway," ",optnum," vs. ", compnum," - cor: ", round(corres,3))) + 
    theme(plot.title = element_text(size = 10))
  return(plot)
}

torun <- c("akt_20", "bad_15", "egfr_10", "her2_10", "igf1r_20", "krasgv_75", "raf_50")
pathcors <- c(get_path_cor(icbp_predictions, "akt_20", torun[1]),
              get_path_cor(icbp_predictions, "bad_250", torun[2]),
              get_path_cor(icbp_predictions, "egfr_50", torun[3]),
              get_path_cor(icbp_predictions, "her2_10", torun[4]),
              get_path_cor(icbp_predictions, "igf1r_100", torun[5]),
              get_path_cor(icbp_predictions, "krasgv_200", torun[6]),
              get_path_cor(icbp_predictions, "raf_350", torun[7]))
corbardata <- data.frame(Sample=factor(torun, levels = torun), Cor=pathcors)
resultplots <- list(create_correlation_plot(icbp_predictions, "akt_20", torun[1]),
                 create_correlation_plot(icbp_predictions, "bad_250", torun[2]),
                 create_correlation_plot(icbp_predictions, "egfr_50", torun[3]),
                 create_correlation_plot(icbp_predictions, "her2_10", torun[4]),
                 create_correlation_plot(icbp_predictions, "igf1r_100", torun[5]),
                 create_correlation_plot(icbp_predictions, "krasgv_200", torun[6]),
                 create_correlation_plot(icbp_predictions, "raf_350", torun[7]))
do.call(grid.arrange, resultplots)
pdf("figure_S1a_icbp.pdf", width = 10, height = 7)
do.call(grid.arrange, resultplots)
dev.off()
```

## TCGA


```{r warning=FALSE, message=FALSE, fig.height=12, fig.width=12}
pathcors <- c(get_path_cor(tcga_predictions, "akt_20", torun[1]),
              get_path_cor(tcga_predictions, "bad_250", torun[2]),
              get_path_cor(tcga_predictions, "egfr_50", torun[3]),
              get_path_cor(tcga_predictions, "her2_10", torun[4]),
              get_path_cor(tcga_predictions, "igf1r_100", torun[5]),
              get_path_cor(tcga_predictions, "krasgv_200", torun[6]),
              get_path_cor(tcga_predictions, "raf_350", torun[7]))
corbardata <- data.frame(Sample=factor(torun, levels = torun), Cor=pathcors)
resultplots <- list(create_correlation_plot(tcga_predictions, "akt_20", torun[1]),
                 create_correlation_plot(tcga_predictions, "bad_250", torun[2]),
                 create_correlation_plot(tcga_predictions, "egfr_50", torun[3]),
                 create_correlation_plot(tcga_predictions, "her2_10", torun[4]),
                 create_correlation_plot(tcga_predictions, "igf1r_100", torun[5]),
                 create_correlation_plot(tcga_predictions, "krasgv_200", torun[6]),
                 create_correlation_plot(tcga_predictions, "raf_350", torun[7]))
do.call(grid.arrange, resultplots)
pdf("figure_S1b_tcga.pdf", width = 10, height = 7)
do.call(grid.arrange, resultplots)
dev.off()
```
